"""add analysis snapshots table

Revision ID: 36a2426cfbf9
Revises: 53b709e7a795
Create Date: 2026-08-22 12:52:26.520338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a2426cfbf9'
down_revision: Union[str, Sequence[str], None] = '53b709e7a795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('contributors_count', sa.Integer(), nullable=False),
    sa.Column('commits_last_7_days', sa.Integer(), nullable=False),
    sa.Column('commits_last_30_days', sa.Integer(), nullable=False),
    sa.Column('activity_level', sa.String(length=50), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_snapshots_repository_analyzed_at', 'analysis_snapshots', ['repository_id', 'analyzed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_snapshots_repository_analyzed_at', table_name='analysis_snapshots')
    op.drop_table('analysis_snapshots')
    # ### end Alembic commands ###
