"""create repositories table

Revision ID: 53b709e7a795
Revises: 
Create Date: 2026-08-20 13:34:35.329903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b709e7a795'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_owner', sa.String(length=255), nullable=False),
    sa.Column('github_name', sa.String(length=255), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=False),
    sa.Column('is_tracked', sa.Boolean(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_repository_url'), 'repositories', ['repository_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositories_repository_url'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
